### ISSUE TITLE
Traceback issue

### ISSUE THREAD

**Issue by Trawleri** [TurfuFrogy/EzQR#2]
i keep getting the issue

Traceback (most recent call last)
 File "c:\Users\(My user\desktop\ezqr-main\main.py", line 47, in <module>
  bot = discord.Bot(intents=discord.Intents.all())
AttributeError: module 'discord' has no attribute 'Bot;\

im confused how do i fix?

**Comment by TurfuFrogy** [comment]
Uninstall discord.py and install pycord using the requirements.txt file.
